### ISSUE TITLE
Agency assumes 'log' attribute is present in Agent

### ISSUE THREAD

**Issue by mickeynp** [oisinmulvihill/evasion-director#1]
Run an Agent without a valid 'log' attribute object in its class and an exception is thrown

Traceback (most recent call last):
  File "/home/mickey/.envs/dev/local/lib/python2.7/site-packages/evasion_agency-1.1.3-py2.7.egg/evasion/agency/manager.py", line 172, in setUp
    a.mod.setUp(a.config)
  File "/home/mickey/projects/imagination/frmi-analytics-amazon-adapters/imagination/analytics/amazonadapters/snslistener.py", line 64, in setUp
    service.WebServerAgent.setUp(self, config)
  File "/home/mickey/.envs/dev/local/lib/python2.7/site-packages/evasion_agency-1.1.3-py2.7.egg/evasion/agency/agents/base/service.py", line 283, in setUp
    self.log.exception("Service creation failed - ")
AttributeError: 'Agent' object has no attribute 'log'
<Agent: name:analytics_amazonsns_listener agent order:1 disabled:no> setUp error:   File "/home/mickey/.envs/dev/local/lib/python2.7/site-packages/evasion_agency-1.1.3-py2.7.egg/evasion/agency/manager.py", line 172, in setUp
    a.mod.setUp(a.config)
  File "/home/mickey/projects/imagination/frmi-analytics-amazon-adapters/imagination/analytics/amazonadapters/snslistener.py", line 64, in setUp
    service.WebServerAgent.setUp(self, config)
  File "/home/mickey/.envs/dev/local/lib/python2.7/site-packages/evasion_agency-1.1.3-py2.7.egg/evasion/agency/agents/base/service.py", line 283, in setUp
    self.log.exception("Service creation failed - ")
2011-11-04 14:28:32,320 analytics.logcaptureagent.agent.

**Comment by oisinmulvihill** [comment]
I'm going to roll this into the 1.1.4 release I'm working on.
